version: '3.8'
services:
  db:
    image: 'postgres:16-alpine'
    env_file: '.env'
    restart: always
    shm_size: 128mb
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  api:
    build: .
    depends_on: ['db']
    environment:
      - PORT=1234
      - DB_URL='db'
      - JWT_SECRET='secret'
    ports:
      - '8080:1234'
